### PR TITLE
Update Neo4J to 3.0.0

### PR DESCRIPTION
**Pull request by bnjdpn**

### CODE REVIEW

**Comment by joel-costigliola** [comment]
Thanks ! it is great to see someone moving this project to neo4j 3.0 as I don't have the time to do so.
I need to setup a CI build for the future PR.

**Comment by fbiville** [comment]
Hey @joel-costigliola , I paired yesterday on this during the Paris Hackergarten ;-)
I can take care of the CI if you want :)

**Comment by fbiville** [comment]
Hey @bnjdpn, thanks for the contribution :)
If you rebase your local repo's master branch against the reference repo's master, you should get the Travis file.
@joel-costigliola all you need to do then is to enable the project (it should appear in https://travis-ci.org/profile/joel-costigliola)

**Comment by joel-costigliola** [comment]
@fbiville project enabled

**Comment by fbiville** [comment]
Thx PR merged via 1ed0992a9bdd23a6b5c18589cebbea3e8ba3d709

**Pull request closed without merging**
